Add networking support for Go applications
unikraft/app-helloworld-go pull request #11
Opened 2023-08-31 21:14 UTC by razvand

Add networking support for Go applications. Demonstrate using `server.go`, a simple HTTP-like server written in Go.

To build `server.go`, first uncomment the line in `Makefile.uk` (and comment out the `helloworld.go` line.

Then, build the Unikraft image:
    
```console
kraft build --kraftfile kraft.cloud.yaml
```
    
Run the Unikraft Go server image:
    
```console
sudo kraft net rm kraft0
sudo kraft net create -n 172.44.0.1/24 kraft0
sudo kraft run --kraftfile kraft.cloud.yaml --plat firecracker --network bridge:kraft0 --initrd ./fs0 -M 256M -a netdev.ipv4_addr=172.44.0.2 -a netdev.ipv4_gw_addr=172.44.0.1 -a netdev.ipv4_subnet_mask=255.255.255.0 -- "server"
```

2023-09-01 07:12 UTC, craciunoiuc approved these changes
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

2023-09-01 08:01 UTC, StefanJum requested changes
@razvand you left an unclosed bracket in the commit message `(and comment out the helloworld.go line)`.

Besides that, what is the `fs0` initrd directory? If it's not needed remove it from the run command in the commit message.

2023-09-04 13:08 UTC, mschlumpp commented on server.go
It might be a good idea to run `go fmt` on the file. The file isn't formatted according to the official Go style.

2023-09-04 13:11 UTC, StefanJum approved these changes
Works fine, I'll add the tag after you format the server file, as @mschlumpp suggested.

2023-09-04 14:02 UTC, razvand commented
@StefanJum , @mschlumpp , fixed.

2023-09-04 14:06 UTC, StefanJum approved these changes
All good, thanks.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-09-04 14:06 UTC, mschlumpp approved these changes
Edit: I haven't noticed that I was assigned ^^

Reviewed-by: Marco Schlumpp <marco@unikraft.io>
Approved-by: Marco Schlumpp <marco@unikraft.io>

2023-09-04 14:40 UTC, closed without merging